// Code generated by tools/gen-seam.go; DO NOT EDIT.

// Re-declared rather than aliased: a type alias carries no values, and a
// consumer compares against these directly (BinOpAdd, ImportStmt, ...).
//
// A constant appears here exactly when its type appears in export.go, so the
// values of every enum a consumer can hold are nameable.
package jsast

import (
	esast "github.com/bytevet/esbuild-jsast/internal/ast"
	"github.com/bytevet/esbuild-jsast/internal/js_ast"
	"github.com/bytevet/esbuild-jsast/internal/logger"
)

// AssertOrWithKeyword
const (
	AssertKeyword = esast.AssertKeyword
	WithKeyword   = esast.WithKeyword
)

// ImportItemStatus
const (
	ImportItemNone      = esast.ImportItemNone
	ImportItemGenerated = esast.ImportItemGenerated
	ImportItemMissing   = esast.ImportItemMissing
)

// ImportKind
const (
	ImportEntryPoint     = esast.ImportEntryPoint
	ImportStmt           = esast.ImportStmt
	ImportRequire        = esast.ImportRequire
	ImportDynamic        = esast.ImportDynamic
	ImportRequireResolve = esast.ImportRequireResolve
	ImportAt             = esast.ImportAt
	ImportComposesFrom   = esast.ImportComposesFrom
	ImportURL            = esast.ImportURL
)

// ImportPhase
const (
	EvaluationPhase = esast.EvaluationPhase
	DeferPhase      = esast.DeferPhase
	SourcePhase     = esast.SourcePhase
)

// ImportRecordFlags
const (
	IsUnused                      = esast.IsUnused
	ContainsImportStar            = esast.ContainsImportStar
	ContainsDefaultAlias          = esast.ContainsDefaultAlias
	ContainsESModuleAlias         = esast.ContainsESModuleAlias
	CallsRunTimeReExportFn        = esast.CallsRunTimeReExportFn
	WrapWithToESM                 = esast.WrapWithToESM
	WrapWithToCJS                 = esast.WrapWithToCJS
	CallRuntimeRequire            = esast.CallRuntimeRequire
	HandlesImportErrors           = esast.HandlesImportErrors
	WasOriginallyBareImport       = esast.WasOriginallyBareImport
	IsExternalWithoutSideEffects  = esast.IsExternalWithoutSideEffects
	AssertTypeJSON                = esast.AssertTypeJSON
	ShouldNotBeExternalInMetafile = esast.ShouldNotBeExternalInMetafile
	WasLoadedWithEmptyLoader      = esast.WasLoadedWithEmptyLoader
	ContainsUniqueKey             = esast.ContainsUniqueKey
)

// SymbolFlags
const (
	MustNotBeRenamed                     = esast.MustNotBeRenamed
	MustStartWithCapitalLetterForJSX     = esast.MustStartWithCapitalLetterForJSX
	DidKeepName                          = esast.DidKeepName
	PrivateSymbolMustBeLowered           = esast.PrivateSymbolMustBeLowered
	RemoveOverwrittenFunctionDeclaration = esast.RemoveOverwrittenFunctionDeclaration
	DidWarnAboutCommonJSInESM            = esast.DidWarnAboutCommonJSInESM
	CouldPotentiallyBeMutated            = esast.CouldPotentiallyBeMutated
	WasExported                          = esast.WasExported
	IsEmptyFunction                      = esast.IsEmptyFunction
	IsIdentityFunction                   = esast.IsIdentityFunction
	CallCanBeUnwrappedIfUnused           = esast.CallCanBeUnwrappedIfUnused
)

// SymbolKind
const (
	SymbolUnbound                    = esast.SymbolUnbound
	SymbolHoisted                    = esast.SymbolHoisted
	SymbolHoistedFunction            = esast.SymbolHoistedFunction
	SymbolCatchIdentifier            = esast.SymbolCatchIdentifier
	SymbolGeneratorOrAsyncFunction   = esast.SymbolGeneratorOrAsyncFunction
	SymbolArguments                  = esast.SymbolArguments
	SymbolClass                      = esast.SymbolClass
	SymbolClassInComputedPropertyKey = esast.SymbolClassInComputedPropertyKey
	SymbolPrivateField               = esast.SymbolPrivateField
	SymbolPrivateMethod              = esast.SymbolPrivateMethod
	SymbolPrivateGet                 = esast.SymbolPrivateGet
	SymbolPrivateSet                 = esast.SymbolPrivateSet
	SymbolPrivateGetSetPair          = esast.SymbolPrivateGetSetPair
	SymbolPrivateStaticField         = esast.SymbolPrivateStaticField
	SymbolPrivateStaticMethod        = esast.SymbolPrivateStaticMethod
	SymbolPrivateStaticGet           = esast.SymbolPrivateStaticGet
	SymbolPrivateStaticSet           = esast.SymbolPrivateStaticSet
	SymbolPrivateStaticGetSetPair    = esast.SymbolPrivateStaticGetSetPair
	SymbolLabel                      = esast.SymbolLabel
	SymbolTSEnum                     = esast.SymbolTSEnum
	SymbolTSNamespace                = esast.SymbolTSNamespace
	SymbolImport                     = esast.SymbolImport
	SymbolConst                      = esast.SymbolConst
	SymbolInjected                   = esast.SymbolInjected
	SymbolMangledProp                = esast.SymbolMangledProp
	SymbolGlobalCSS                  = esast.SymbolGlobalCSS
	SymbolLocalCSS                   = esast.SymbolLocalCSS
	SymbolOther                      = esast.SymbolOther
)

// AnnotationFlags
const (
	CanBeRemovedIfUnusedFlag = js_ast.CanBeRemovedIfUnusedFlag
)

// AssignTarget
const (
	AssignTargetNone    = js_ast.AssignTargetNone
	AssignTargetReplace = js_ast.AssignTargetReplace
	AssignTargetUpdate  = js_ast.AssignTargetUpdate
)

// CallKind
const (
	NormalCall                        = js_ast.NormalCall
	DirectEval                        = js_ast.DirectEval
	TargetWasOriginallyPropertyAccess = js_ast.TargetWasOriginallyPropertyAccess
)

// ConstValueKind
const (
	ConstValueNone      = js_ast.ConstValueNone
	ConstValueNull      = js_ast.ConstValueNull
	ConstValueUndefined = js_ast.ConstValueUndefined
	ConstValueTrue      = js_ast.ConstValueTrue
	ConstValueFalse     = js_ast.ConstValueFalse
	ConstValueNumber    = js_ast.ConstValueNumber
	ConstValueString    = js_ast.ConstValueString
)

// EqualityKind
const (
	LooseEquality  = js_ast.LooseEquality
	StrictEquality = js_ast.StrictEquality
)

// ExportsKind
const (
	ExportsNone                   = js_ast.ExportsNone
	ExportsCommonJS               = js_ast.ExportsCommonJS
	ExportsESM                    = js_ast.ExportsESM
	ExportsESMWithDynamicFallback = js_ast.ExportsESMWithDynamicFallback
)

// L
const (
	LLowest            = js_ast.LLowest
	LComma             = js_ast.LComma
	LSpread            = js_ast.LSpread
	LYield             = js_ast.LYield
	LAssign            = js_ast.LAssign
	LConditional       = js_ast.LConditional
	LNullishCoalescing = js_ast.LNullishCoalescing
	LLogicalOr         = js_ast.LLogicalOr
	LLogicalAnd        = js_ast.LLogicalAnd
	LBitwiseOr         = js_ast.LBitwiseOr
	LBitwiseXor        = js_ast.LBitwiseXor
	LBitwiseAnd        = js_ast.LBitwiseAnd
	LEquals            = js_ast.LEquals
	LCompare           = js_ast.LCompare
	LShift             = js_ast.LShift
	LAdd               = js_ast.LAdd
	LMultiply          = js_ast.LMultiply
	LExponentiation    = js_ast.LExponentiation
	LPrefix            = js_ast.LPrefix
	LPostfix           = js_ast.LPostfix
	LNew               = js_ast.LNew
	LCall              = js_ast.LCall
	LMember            = js_ast.LMember
)

// LocalKind
const (
	LocalVar        = js_ast.LocalVar
	LocalLet        = js_ast.LocalLet
	LocalConst      = js_ast.LocalConst
	LocalUsing      = js_ast.LocalUsing
	LocalAwaitUsing = js_ast.LocalAwaitUsing
)

// ModuleType
const (
	ModuleUnknown              = js_ast.ModuleUnknown
	ModuleCommonJS_CJS         = js_ast.ModuleCommonJS_CJS
	ModuleCommonJS_CTS         = js_ast.ModuleCommonJS_CTS
	ModuleCommonJS_PackageJSON = js_ast.ModuleCommonJS_PackageJSON
	ModuleESM_MJS              = js_ast.ModuleESM_MJS
	ModuleESM_MTS              = js_ast.ModuleESM_MTS
	ModuleESM_PackageJSON      = js_ast.ModuleESM_PackageJSON
)

// OpCode
const (
	UnOpPos                      = js_ast.UnOpPos
	UnOpNeg                      = js_ast.UnOpNeg
	UnOpCpl                      = js_ast.UnOpCpl
	UnOpNot                      = js_ast.UnOpNot
	UnOpVoid                     = js_ast.UnOpVoid
	UnOpTypeof                   = js_ast.UnOpTypeof
	UnOpDelete                   = js_ast.UnOpDelete
	UnOpPreDec                   = js_ast.UnOpPreDec
	UnOpPreInc                   = js_ast.UnOpPreInc
	UnOpPostDec                  = js_ast.UnOpPostDec
	UnOpPostInc                  = js_ast.UnOpPostInc
	BinOpAdd                     = js_ast.BinOpAdd
	BinOpSub                     = js_ast.BinOpSub
	BinOpMul                     = js_ast.BinOpMul
	BinOpDiv                     = js_ast.BinOpDiv
	BinOpRem                     = js_ast.BinOpRem
	BinOpPow                     = js_ast.BinOpPow
	BinOpLt                      = js_ast.BinOpLt
	BinOpLe                      = js_ast.BinOpLe
	BinOpGt                      = js_ast.BinOpGt
	BinOpGe                      = js_ast.BinOpGe
	BinOpIn                      = js_ast.BinOpIn
	BinOpInstanceof              = js_ast.BinOpInstanceof
	BinOpShl                     = js_ast.BinOpShl
	BinOpShr                     = js_ast.BinOpShr
	BinOpUShr                    = js_ast.BinOpUShr
	BinOpLooseEq                 = js_ast.BinOpLooseEq
	BinOpLooseNe                 = js_ast.BinOpLooseNe
	BinOpStrictEq                = js_ast.BinOpStrictEq
	BinOpStrictNe                = js_ast.BinOpStrictNe
	BinOpNullishCoalescing       = js_ast.BinOpNullishCoalescing
	BinOpLogicalOr               = js_ast.BinOpLogicalOr
	BinOpLogicalAnd              = js_ast.BinOpLogicalAnd
	BinOpBitwiseOr               = js_ast.BinOpBitwiseOr
	BinOpBitwiseAnd              = js_ast.BinOpBitwiseAnd
	BinOpBitwiseXor              = js_ast.BinOpBitwiseXor
	BinOpComma                   = js_ast.BinOpComma
	BinOpAssign                  = js_ast.BinOpAssign
	BinOpAddAssign               = js_ast.BinOpAddAssign
	BinOpSubAssign               = js_ast.BinOpSubAssign
	BinOpMulAssign               = js_ast.BinOpMulAssign
	BinOpDivAssign               = js_ast.BinOpDivAssign
	BinOpRemAssign               = js_ast.BinOpRemAssign
	BinOpPowAssign               = js_ast.BinOpPowAssign
	BinOpShlAssign               = js_ast.BinOpShlAssign
	BinOpShrAssign               = js_ast.BinOpShrAssign
	BinOpUShrAssign              = js_ast.BinOpUShrAssign
	BinOpBitwiseOrAssign         = js_ast.BinOpBitwiseOrAssign
	BinOpBitwiseAndAssign        = js_ast.BinOpBitwiseAndAssign
	BinOpBitwiseXorAssign        = js_ast.BinOpBitwiseXorAssign
	BinOpNullishCoalescingAssign = js_ast.BinOpNullishCoalescingAssign
	BinOpLogicalOrAssign         = js_ast.BinOpLogicalOrAssign
	BinOpLogicalAndAssign        = js_ast.BinOpLogicalAndAssign
)

// OptionalChain
const (
	OptionalChainNone     = js_ast.OptionalChainNone
	OptionalChainStart    = js_ast.OptionalChainStart
	OptionalChainContinue = js_ast.OptionalChainContinue
)

// PrimitiveType
const (
	PrimitiveUnknown   = js_ast.PrimitiveUnknown
	PrimitiveMixed     = js_ast.PrimitiveMixed
	PrimitiveNull      = js_ast.PrimitiveNull
	PrimitiveUndefined = js_ast.PrimitiveUndefined
	PrimitiveBoolean   = js_ast.PrimitiveBoolean
	PrimitiveNumber    = js_ast.PrimitiveNumber
	PrimitiveString    = js_ast.PrimitiveString
	PrimitiveBigInt    = js_ast.PrimitiveBigInt
)

// PropertyFlags
const (
	PropertyIsComputed      = js_ast.PropertyIsComputed
	PropertyIsStatic        = js_ast.PropertyIsStatic
	PropertyWasShorthand    = js_ast.PropertyWasShorthand
	PropertyPreferQuotedKey = js_ast.PropertyPreferQuotedKey
)

// PropertyKind
const (
	PropertyField             = js_ast.PropertyField
	PropertyMethod            = js_ast.PropertyMethod
	PropertyGetter            = js_ast.PropertyGetter
	PropertySetter            = js_ast.PropertySetter
	PropertyAutoAccessor      = js_ast.PropertyAutoAccessor
	PropertySpread            = js_ast.PropertySpread
	PropertyDeclareOrAbstract = js_ast.PropertyDeclareOrAbstract
	PropertyClassStaticBlock  = js_ast.PropertyClassStaticBlock
)

// ScopeKind
const (
	ScopeBlock           = js_ast.ScopeBlock
	ScopeWith            = js_ast.ScopeWith
	ScopeLabel           = js_ast.ScopeLabel
	ScopeClassName       = js_ast.ScopeClassName
	ScopeClassBody       = js_ast.ScopeClassBody
	ScopeCatchBinding    = js_ast.ScopeCatchBinding
	ScopeEntry           = js_ast.ScopeEntry
	ScopeFunctionArgs    = js_ast.ScopeFunctionArgs
	ScopeFunctionBody    = js_ast.ScopeFunctionBody
	ScopeClassStaticInit = js_ast.ScopeClassStaticInit
)

// SideEffects
const (
	CouldHaveSideEffects = js_ast.CouldHaveSideEffects
	NoSideEffects        = js_ast.NoSideEffects
)

// StmtsCanBeRemovedIfUnusedFlags
const (
	KeepExportClauses          = js_ast.KeepExportClauses
	ReturnCanBeRemovedIfUnused = js_ast.ReturnCanBeRemovedIfUnused
)

// StrictModeKind
const (
	SloppyMode                            = js_ast.SloppyMode
	ExplicitStrictMode                    = js_ast.ExplicitStrictMode
	ImplicitStrictModeClass               = js_ast.ImplicitStrictModeClass
	ImplicitStrictModeESM                 = js_ast.ImplicitStrictModeESM
	ImplicitStrictModeTSAlwaysStrict      = js_ast.ImplicitStrictModeTSAlwaysStrict
	ImplicitStrictModeJSXAutomaticRuntime = js_ast.ImplicitStrictModeJSXAutomaticRuntime
)

// StringAdditionKind
const (
	StringAdditionNormal         = js_ast.StringAdditionNormal
	StringAdditionWithNestedLeft = js_ast.StringAdditionWithNestedLeft
)

// PathFlags
const (
	PathDisabled = logger.PathDisabled
)
