// Code generated by tools/gen-walk.go; DO NOT EDIT.

package jsast

// Node is one visited node: the statement, expression or binding data, paired
// with the Loc of the wrapper it was reached through.
//
// Data holds a node kind pointer -- *SExpr, *EDot, *BIdentifier -- so a visitor
// type-switches on it exactly as it would on Stmt.Data.
type Node struct {
	Loc  Loc
	Data any
}

// Inspect traverses stmts in depth-first order, calling f for every statement,
// expression and binding it reaches. If f returns false, that node's children
// are skipped; returning true descends.
//
// A node is visited before its children. Fields following the OrNil convention
// are skipped when empty, so f never sees a Node with nil Data.
func Inspect(stmts []Stmt, f func(Node) bool) {
	for i := range stmts {
		walkStmt(&stmts[i], f)
	}
}

// InspectExpr is Inspect rooted at a single expression.
func InspectExpr(e Expr, f func(Node) bool) { walkExpr(&e, f) }

func walkStmt(stmt *Stmt, f func(Node) bool) {
	if stmt.Data == nil || !f(Node{Loc: stmt.Loc, Data: stmt.Data}) {
		return
	}
	switch n := stmt.Data.(type) {
	case *SBlock:
		for i0 := range n.Stmts {
			walkStmt(&n.Stmts[i0], f)
		}
	case *SClass:
		walkClass(&n.Class, f)
	case *SDoWhile:
		walkStmt(&n.Body, f)
		walkExpr(&n.Test, f)
	case *SEnum:
		for i0 := range n.Values {
			walkEnumValue(&n.Values[i0], f)
		}
	case *SExportDefault:
		walkStmt(&n.Value, f)
	case *SExportEquals:
		walkExpr(&n.Value, f)
	case *SExpr:
		walkExpr(&n.Value, f)
	case *SFor:
		walkStmt(&n.InitOrNil, f)
		walkExpr(&n.TestOrNil, f)
		walkExpr(&n.UpdateOrNil, f)
		walkStmt(&n.Body, f)
	case *SForIn:
		walkStmt(&n.Init, f)
		walkExpr(&n.Value, f)
		walkStmt(&n.Body, f)
	case *SForOf:
		walkStmt(&n.Init, f)
		walkExpr(&n.Value, f)
		walkStmt(&n.Body, f)
	case *SFunction:
		walkFn(&n.Fn, f)
	case *SIf:
		walkExpr(&n.Test, f)
		walkStmt(&n.Yes, f)
		walkStmt(&n.NoOrNil, f)
	case *SLabel:
		walkStmt(&n.Stmt, f)
	case *SLazyExport:
		walkExpr(&n.Value, f)
	case *SLocal:
		for i0 := range n.Decls {
			walkDecl(&n.Decls[i0], f)
		}
	case *SNamespace:
		for i0 := range n.Stmts {
			walkStmt(&n.Stmts[i0], f)
		}
	case *SReturn:
		walkExpr(&n.ValueOrNil, f)
	case *SSwitch:
		walkExpr(&n.Test, f)
		for i0 := range n.Cases {
			walkCase(&n.Cases[i0], f)
		}
	case *SThrow:
		walkExpr(&n.Value, f)
	case *STry:
		if n.Catch != nil {
			walkCatch(&(*n.Catch), f)
		}
		if n.Finally != nil {
			walkFinally(&(*n.Finally), f)
		}
		walkSBlock(&n.Block, f)
	case *SWhile:
		walkExpr(&n.Test, f)
		walkStmt(&n.Body, f)
	case *SWith:
		walkExpr(&n.Value, f)
		walkStmt(&n.Body, f)
	}
}

func walkExpr(expr *Expr, f func(Node) bool) {
	if expr.Data == nil || !f(Node{Loc: expr.Loc, Data: expr.Data}) {
		return
	}
	switch n := expr.Data.(type) {
	case *EAnnotation:
		walkExpr(&n.Value, f)
	case *EArray:
		for i0 := range n.Items {
			walkExpr(&n.Items[i0], f)
		}
	case *EArrow:
		for i0 := range n.Args {
			walkArg(&n.Args[i0], f)
		}
		walkFnBody(&n.Body, f)
	case *EAwait:
		walkExpr(&n.Value, f)
	case *EBinary:
		walkExpr(&n.Left, f)
		walkExpr(&n.Right, f)
	case *ECall:
		walkExpr(&n.Target, f)
		for i0 := range n.Args {
			walkExpr(&n.Args[i0], f)
		}
	case *EClass:
		walkClass(&n.Class, f)
	case *EDot:
		walkExpr(&n.Target, f)
	case *EFunction:
		walkFn(&n.Fn, f)
	case *EIf:
		walkExpr(&n.Test, f)
		walkExpr(&n.Yes, f)
		walkExpr(&n.No, f)
	case *EImportCall:
		walkExpr(&n.Expr, f)
		walkExpr(&n.OptionsOrNil, f)
	case *EIndex:
		walkExpr(&n.Target, f)
		walkExpr(&n.Index, f)
	case *EInlinedEnum:
		walkExpr(&n.Value, f)
	case *EJSXElement:
		walkExpr(&n.TagOrNil, f)
		for i0 := range n.Properties {
			walkProperty(&n.Properties[i0], f)
		}
		for i0 := range n.NullableChildren {
			walkExpr(&n.NullableChildren[i0], f)
		}
	case *ENew:
		walkExpr(&n.Target, f)
		for i0 := range n.Args {
			walkExpr(&n.Args[i0], f)
		}
	case *EObject:
		for i0 := range n.Properties {
			walkProperty(&n.Properties[i0], f)
		}
	case *ESpread:
		walkExpr(&n.Value, f)
	case *ETemplate:
		walkExpr(&n.TagOrNil, f)
		for i0 := range n.Parts {
			walkTemplatePart(&n.Parts[i0], f)
		}
	case *EUnary:
		walkExpr(&n.Value, f)
	case *EYield:
		walkExpr(&n.ValueOrNil, f)
	}
}

func walkBinding(binding *Binding, f func(Node) bool) {
	if binding.Data == nil || !f(Node{Loc: binding.Loc, Data: binding.Data}) {
		return
	}
	switch n := binding.Data.(type) {
	case *BArray:
		for i0 := range n.Items {
			walkArrayBinding(&n.Items[i0], f)
		}
	case *BObject:
		for i0 := range n.Properties {
			walkPropertyBinding(&n.Properties[i0], f)
		}
	}
}

func walkArg(v *Arg, f func(Node) bool) {
	walkBinding(&v.Binding, f)
	walkExpr(&v.DefaultOrNil, f)
	for i0 := range v.Decorators {
		walkDecorator(&v.Decorators[i0], f)
	}
}

func walkArrayBinding(v *ArrayBinding, f func(Node) bool) {
	walkBinding(&v.Binding, f)
	walkExpr(&v.DefaultValueOrNil, f)
}

func walkCase(v *Case, f func(Node) bool) {
	walkExpr(&v.ValueOrNil, f)
	for i0 := range v.Body {
		walkStmt(&v.Body[i0], f)
	}
}

func walkCatch(v *Catch, f func(Node) bool) {
	walkBinding(&v.BindingOrNil, f)
	walkSBlock(&v.Block, f)
}

func walkClass(v *Class, f func(Node) bool) {
	for i0 := range v.Decorators {
		walkDecorator(&v.Decorators[i0], f)
	}
	walkExpr(&v.ExtendsOrNil, f)
	for i0 := range v.Properties {
		walkProperty(&v.Properties[i0], f)
	}
}

func walkDecl(v *Decl, f func(Node) bool) {
	walkBinding(&v.Binding, f)
	walkExpr(&v.ValueOrNil, f)
}

func walkEnumValue(v *EnumValue, f func(Node) bool) {
	walkExpr(&v.ValueOrNil, f)
}

func walkFinally(v *Finally, f func(Node) bool) {
	walkSBlock(&v.Block, f)
}

func walkFn(v *Fn, f func(Node) bool) {
	for i0 := range v.Args {
		walkArg(&v.Args[i0], f)
	}
	walkFnBody(&v.Body, f)
}

func walkFnBody(v *FnBody, f func(Node) bool) {
	walkSBlock(&v.Block, f)
}

func walkProperty(v *Property, f func(Node) bool) {
	if v.ClassStaticBlock != nil {
		walkClassStaticBlock(&(*v.ClassStaticBlock), f)
	}
	walkExpr(&v.Key, f)
	walkExpr(&v.ValueOrNil, f)
	walkExpr(&v.InitializerOrNil, f)
	for i0 := range v.Decorators {
		walkDecorator(&v.Decorators[i0], f)
	}
}

func walkPropertyBinding(v *PropertyBinding, f func(Node) bool) {
	walkExpr(&v.Key, f)
	walkBinding(&v.Value, f)
	walkExpr(&v.DefaultValueOrNil, f)
}

func walkSBlock(v *SBlock, f func(Node) bool) {
	for i0 := range v.Stmts {
		walkStmt(&v.Stmts[i0], f)
	}
}

func walkTemplatePart(v *TemplatePart, f func(Node) bool) {
	walkExpr(&v.Value, f)
}

func walkClassStaticBlock(v *ClassStaticBlock, f func(Node) bool) {
	walkSBlock(&v.Block, f)
}

func walkDecorator(v *Decorator, f func(Node) bool) {
	walkExpr(&v.Value, f)
}
